server:
  port: 8080

logging: # Log 관련 설정. DEBUG로 출력하겠다는 옵션
  level:
    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true
  messages:
    basename: messages
  security:
    user:
      name: username
      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"
